import { Metadata } from "next";
import { Manrope, Source_Serif_4, IBM_Plex_Mono } from "next/font/google";

// UI/body font - buttons, labels, nav, everything that isn't a hero
// number or a page title.
export const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

// Display/serif font - hero balance numbers and page titles only. Variable
// (opsz axis), so no weight array needed.
export const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  display: "swap",
});

// Tabular data font - amounts, percentages, dates in lists/tables. Not a
// variable font on Google Fonts, so the weights actually used need listing.
export const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
